### ISSUE TITLE
Doesn't load Messages on M1 Mac

### ISSUE THREAD

**Issue by git-kevin-kumar** [slatinsky/DiscordChatExporter-frontend#32]
Already starts with mongodb not supported (even tho I don't understand why you would need a database do display local files).

Here are the logs if needed, as you have written you are not sure if its compatible. I just wanted to provide some information. You can close the issue ^^

Last login: Sun Jul 23 13:36:04 on ttys003
MacBook-Air-von-Kevin Backup % docker run --volume "$(pwd):/dcef/exports" --volume dcef_cache:/dcef/cache --rm --name dcef -p 21011:21011 -it slada/dcef:main
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

main_mongo loaded
Connecting to database...
Traceback (most recent call last):
  File "/dcef/backend/preprocess/main_mongo.py", line 80, in <module>
    main(input_dir, output_dir)
  File "/dcef/backend/preprocess/main_mongo.py", line 50, in main
    database = MongoDatabase()
               ^^^^^^^^^^^^^^^
  File "/dcef/backend/preprocess/MongoDatabase.py", line 27, in __init__
    self.create_indexes()
  File "/dcef/backend/preprocess/MongoDatabase.py", line 32, in create_indexes
    self.col["messages"].create_index("channelId", default_language="none")
  File "/usr/local/lib/python3.11/dist-packages/pymongo/collection.py", line 2055, in create_index
    return self.__create_indexes([index], session, **cmd_options)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/collection.py", line 1911, in __create_indexes
    with self._socket_for_writes(session) as sock_info:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/collection.py", line 248, in _socket_for_writes
    return self.__database.client._socket_for_writes(session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/mongo_client.py", line 1267, in _socket_for_writes
    server = self._select_server(writable_server_selector, session)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/mongo_client.py", line 1257, in _select_server
    server = topology.select_server(server_selector)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 272, in select_server
    server = self._select_server(selector, server_selection_timeout, address)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 261, in _select_server
    servers = self.select_servers(selector, server_selection_timeout, address)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 223, in select_servers
    server_descriptions = self._select_servers_loop(selector, server_timeout, address)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 64bd10cd1634855f63a3b7d4, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused')>]>
############################################################
# Open http://127.0.0.1:21011/ in your browser to view GUI #
############################################################
2023/07/23 11:37:16 [notice] 38#38: using the "epoll" event method
2023/07/23 11:37:16 [notice] 38#38: nginx/1.18.0 (Ubuntu)
2023/07/23 11:37:16 [notice] 38#38: OS: Linux 5.15.49-linuxkit
2023/07/23 11:37:16 [notice] 38#38: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/07/23 11:37:16 [notice] 38#38: start worker processes
2023/07/23 11:37:16 [notice] 38#38: start worker process 41
INFO:     Started server process [35]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:58000 (Press CTRL+C to quit)
INFO:     172.17.0.1:0 - "GET /guilds HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dcef/backend/fastapi/app.py", line 102, in get_guilds
    return list(cursor)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 64bd10ee492cb8404f48613b, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused')>]>
INFO:     172.17.0.1:0 - "GET /guilds HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dcef/backend/fastapi/app.py", line 102, in get_guilds
    return list(cursor)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 64bd10ee492cb8404f48613b, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused')>]>
2023/07/23 11:38:40 [error] 41#41: *8 open() "/dcef/cache/preprocess/fonts/ggsans-normal-400.woff2" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /data/fonts/ggsans-normal-400.woff2 HTTP/1.1", host: "127.0.0.1:21011", referrer: "http://127.0.0.1:21011/_app/immutable/assets/_layout-2d954d72.css"
2023/07/23 11:38:40 [error] 41#41: *9 open() "/dcef/cache/preprocess/fonts/ggsans-normal-700.woff2" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /data/fonts/ggsans-normal-700.woff2 HTTP/1.1", host: "127.0.0.1:21011", referrer: "http://127.0.0.1:21011/_app/immutable/assets/_layout-2d954d72.css"
2023/07/23 11:38:56 [error] 41#41: *8 open() "/dcef/cache/preprocess/fonts/ggsans-normal-600.woff2" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /data/fonts/ggsans-normal-600.woff2 HTTP/1.1", host: "127.0.0.1:21011", referrer: "http://127.0.0.1:21011/_app/immutable/assets/_layout-2d954d72.css"
2023/07/23 11:38:56 [error] 41#41: *9 open() "/dcef/cache/preprocess/fonts/ggsans-normal-500.woff2" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /data/fonts/ggsans-normal-500.woff2 HTTP/1.1", host: "127.0.0.1:21011", referrer: "http://127.0.0.1:21011/_app/immutable/assets/_layout-2d954d72.css"
2023/07/23 11:39:03 [error] 41#41: *6 open() "/dcef/cache/preprocess/fonts/ggsans-normal-400.woff2" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /data/fonts/ggsans-normal-400.woff2 HTTP/1.1", host: "localhost:21011", referrer: "http://localhost:21011/_app/immutable/assets/_layout-2d954d72.css"
2023/07/23 11:39:03 [error] 41#41: *15 open() "/dcef/cache/preprocess/fonts/ggsans-normal-700.woff2" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /data/fonts/ggsans-normal-700.woff2 HTTP/1.1", host: "localhost:21011", referrer: "http://localhost:21011/_app/immutable/assets/_layout-2d954d72.css"
2023/07/23 11:39:03 [error] 41#41: *16 open() "/dcef/cache/preprocess/fonts/ggsans-normal-500.woff2" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /data/fonts/ggsans-normal-500.woff2 HTTP/1.1", host: "localhost:21011", referrer: "http://localhost:21011/_app/immutable/assets/_layout-2d954d72.css"
2023/07/23 11:39:03 [error] 41#41: *17 open() "/dcef/cache/preprocess/fonts/ggsans-normal-600.woff2" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /data/fonts/ggsans-normal-600.woff2 HTTP/1.1", host: "localhost:21011", referrer: "http://localhost:21011/_app/immutable/assets/_layout-2d954d72.css"
2023/07/23 11:40:38 [notice] 41#41: signal 28 (SIGWINCH) received
2023/07/23 11:40:38 [notice] 38#38: signal 28 (SIGWINCH) received
2023/07/23 11:40:38 [info] 41#41: epoll_wait() failed (4: Interrupted system call)
2023/07/23 11:40:38 [notice] 38#38: signal 28 (SIGWINCH) received
2023/07/23 11:40:38 [notice] 41#41: signal 28 (SIGWINCH) received
2023/07/23 11:40:38 [info] 41#41: epoll_wait() failed (4: Interrupted system call)
2023/07/23 11:40:38 [notice] 38#38: signal 28 (SIGWINCH) received
2023/07/23 11:40:38 [notice] 41#41: signal 28 (SIGWINCH) received
2023/07/23 11:40:38 [info] 41#41: epoll_wait() failed (4: Interrupted system call)
2023/07/23 11:40:38 [notice] 38#38: signal 28 (SIGWINCH) received
2023/07/23 11:40:38 [notice] 41#41: signal 28 (SIGWINCH) received
2023/07/23 11:40:38 [info] 41#41: epoll_wait() failed (4: Interrupted system call)
2023/07/23 11:40:38 [notice] 38#38: signal 28 (SIGWINCH) received
2023/07/23 11:40:38 [notice] 41#41: signal 28 (SIGWINCH) received
2023/07/23 11:40:38 [info] 41#41: epoll_wait() failed (4: Interrupted system call)
2023/07/23 11:40:38 [notice] 41#41: signal 28 (SIGWINCH) received

**Comment by slatinsky** [comment]
Hello,

I don't have M1 Mac to debug this, but this change in Dockerfile may help you
https://github.com/slatinsky/DiscordChatExporter-frontend/pull/30/files

**Comment by Mattlau04** [comment]
Same error here, under Arch Linux

**Comment by Mattlau04** [comment]
Same error here, under Arch Linux
However, i'm not under arm (`uname -m` gives `x86_64`), so the proposed fix doesn't work...
Is using Mongo DB truly necessary?

**Comment by slatinsky** [comment]
Hello @Mattlau04,

I have just released a new version, which fixes some crashes. If you have any issues with this new version, please create a new issue to keep this issue only for macs. And please include logs if you can.

DCEF is currently tested by me in these two configurations:
- Windows binary build + clean Windows 10 virtual machine
- Ubuntu 22.04 (no gui) + docker + built docker image from dockerhub
