### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by Davilarek** [slatinsky/DiscordChatExporter-frontend#36]
I have an raspberry pi 4 (arm64) and the docker container exits because of wrong cpu arch
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```
is there a workaround?

**Comment by slatinsky** [comment]
Hello, I currently don't have a raspberry pi to test near me. Maybe this change meant for mac will work for raspberry pi too?: https://github.com/slatinsky/DiscordChatExporter-frontend/pull/30/files

**Comment by Davilarek** [comment]
how can I replace that docker file?

**Comment by slatinsky** [comment]
You need to build it from source. `Build docker image from source code` in [README.md](https://github.com/slatinsky/DiscordChatExporter-frontend).

Make changes to dockerfile feborr you run `docker build -t dcef .`

**Comment by Davilarek** [comment]
huh. I didn't notice that section.
anyway, after building and running, I get this error
```
INFO:     192.168.1.33:0 - "GET /guilds HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dcef/backend/fastapi/app.py", line 103, in get_guilds
    return list(cursor)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.11/dist-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 64f3318f1750ddf3c3729c9e, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused')>]>
2023/09/02 12:59:56 [error] 19#19: *6 open() "/dcef/cache/preprocess/fonts/ggsans-normal-400.woff2" failed (2: No such file or directory), client: 192.168.1.33, server: localhost, request: "GET /data/fonts/ggsans-normal-400.woff2 HTTP/1.1", host: "192.168.1.61:21011", referrer: "http://192.168.1.61:21011/_app/immutable/assets/_layout-92ac35d3.css"
2023/09/02 12:59:56 [error] 19#19: *6 open() "/dcef/cache/preprocess/fonts/ggsans-normal-700.woff2" failed (2: No such file or directory), client: 192.168.1.33, server: localhost, request: "GET /data/fonts/ggsans-normal-700.woff2 HTTP/1.1", host: "192.168.1.61:21011", referrer: "http://192.168.1.61:21011/_app/immutable/assets/_layout-92ac35d3.css"
```
I use the command
```
sudo docker run --volume "$(pwd):/dcef/exports" --volume dcef_cache:/dcef/cache --name dcef -p 21011:21011 -it dcef:latest
```

**Comment by slatinsky** [comment]
It looks like mongodb didn't start up, so pymongo cannot connect to it.

I will debug this later with raspberry pi 4b, but it will take ~2 weeks till I get one.

**Comment by Davilarek** [comment]
See Edit2, I may installed the wrong mongoDB

**Comment by slatinsky** [comment]
It looks like mongodb doesn't support `ARMv8.0-A` architecture, which raspberry pi 4b uses (MongoDB requires `ARMv8.2-A` or higher). Last mongodb version that will run on raspberry pi is [4.4.x](https://stackoverflow.com/questions/68419196/mongodb-versions-5-x-on-arm64-architecture-minimum-armv8-2-a-required)

I found unofficial mongodb builds for  `ARMv8.0-A` architecture, not tested:
https://github.com/themattman/mongodb-raspberrypi-binaries
https://github.com/themattman/mongodb-raspberrypi-docker

**Comment by Davilarek** [comment]
how can I use that?

**Comment by slatinsky** [comment]
Hello,

I have added dockerfile to build the project on raspberry pi 4b. Run this command to build the project for ARM Cortex-A72 CPU:

```bash
docker build -t dcef -f Dockerfile.rpi4b
````

tested on:
```
OS: Debian GNU/Linux 11 (bullseye) aarch64
Host: Raspberry Pi 4 Model B Rev 1.4
```

**Comment by Davilarek** [comment]
works now, thanks :+1:
