### ISSUE TITLE
Traceback (guilds not appearing)

### ISSUE THREAD

**Issue by zyradyl** [slatinsky/DiscordChatExporter-frontend#43]
## Expected Behavior
Application starts
...

## Actual Behavior
See logs and notes
...

## Steps to reproduce the problem

  1. Download docker image
  2. Attempt to run
  3. (See notes)

### Environment

  - Operating system: Linux (see comments
  - CPU Architecture: x86_64 (PC)
  - Flavor: Docker

### DiscordChatExporter-frontend

  - [Release](https://github.com/slatinsky/DiscordChatExporter-frontend/releases) version or commit hash: docker hash -  c31fe828b048 (most recent main)
  - Can the issue be reproduced in the [demo](https://dcef.slada.sk/)?: Don't know

### [DiscordChatExporter](https://github.com/Tyrrrz/DiscordChatExporter)

- Version (CLI `--version`): v2.42.2

How did you export the data?
  - Export format (CLI `--format`): Json
  - Downloaded assets (CLI `--media`): Yes (and --reuse-media_
  - Markdown processing (CLI `--markdown`): set to false
  - Other CLI options (optional): ...

  

## Logs

Is there any relevant information in logs? If so, please provide them:

```
2023-11-05 04:49:44.915173+00:00[Preprocess] took 0.64 seconds
2023-11-05 04:49:44.915217+00:00Traceback (most recent call last):
2023-11-05 04:49:44.915228+00:00File "/dcef/backend/preprocess/main_mongo.py", line 146, in <module>
2023-11-05 04:49:44.915368+00:00main(input_dir, output_dir)
2023-11-05 04:49:44.915413+00:00File "/dcef/backend/preprocess/main_mongo.py", line 119, in main
2023-11-05 04:49:44.915485+00:00channel_cache = ChannelCache()
2023-11-05 04:49:44.915507+00:00^^^^^^^^^^^^^^
2023-11-05 04:49:44.915521+00:00File "/dcef/backend/preprocess/ChannelCache.py", line 22, in __init__
2023-11-05 04:49:44.915568+00:00os.makedirs(self.cache_folder_path)
2023-11-05 04:49:44.915594+00:00File "<frozen os>", line 215, in makedirs
2023-11-05 04:49:44.915605+00:00File "<frozen os>", line 215, in makedirs
2023-11-05 04:49:44.915617+00:00File "<frozen os>", line 215, in makedirs
2023-11-05 04:49:44.915624+00:00[Previous line repeated 1 more time]
2023-11-05 04:49:44.915630+00:00File "<frozen os>", line 225, in makedirs
2023-11-05 04:49:44.915636+00:00OSError: [Errno 30] Read-only file system: '../../release'
```

**Notes**

This is actually running on a TrueNAS SCALE system, which is a debian linux appliance that runs a kubernetes cluster. I've ran into a few weird readonly errors prior to this but was able to resolve them. After I saw the most recent commit was to fix the docker image, I also made sure to pull the image by sha256 digest to make sure it was the most up to date.

`/dcef/cache` -> PVC Volume
`/dcef/exports` -> points to my DCE exports directory. Exports were generated with incremental chat exporter.
`/var/lib/nginx` -> PVC Volume (without this, /var/lib/nginx/body can't be written, NGINX throws an EMERG error and the container quits)
`/var/log/nginx` -> PVC Volume (without this, being unable to write access.log triggers an EMERG error and container quits)

The container is running as uid/gid 0/0 (root) as without this an error is thrown. Ports are mapped 21011 to 21011, which then feeds into a kubernetes ingress controller. Access works fine, webpage loads fine, it's only loading the guilds that fails.

I know this is probably beyond what was intended, so if there's anyway I can help let me know.

**Comment by zyradyl** [comment]
Hey got it working. If i mount a PVC volume to `/dcef/release/dcef/storage/cache/message-ids` everything begins to work. I got this path from ChannelCache.py and the run_container script. Is there any way that this directory could be moved into `/dcef/cache` along with maybe nginx logs and nginx/body?

**Comment by slatinsky** [comment]
Hello, as mentioned in [your pull request #44](https://github.com/slatinsky/DiscordChatExporter-frontend/pull/44#issuecomment-1793748613), project needs bigger folder restructure to fix this issue. Please use your workaround for now.
